version: '3.8'

services:
  analysis-nginx:
    container_name: analysis-nginx
    image: nginx:1.21.3
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - analysis-app
    volumes:
      - ${APP_PATH}:/usr/local/www/data/${APP_NAME}
      - ${NGINX_PATH}conf.d/:/etc/nginx/conf.d/
      - ${NGINX_PATH}/nginx.conf/:/etc/nginx/nginx.conf/

  analysis-app:
    container_name: analysis-app
    build:
      context: images/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /usr/local/www/data/${APP_NAME}
    depends_on:
      - analysis-db
    volumes:
      - ${APP_PATH}:${ANALYSIS_PATH}

  analysis-db:
    container_name: analysis-db
    image: percona:5.7.35
    build:
      context: images/percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#      - ${DB_PATH}:/var/lib/mysql

  analysis-adminer:
    container_name: analysis-adminer
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: analysis-db
    ports:
      - '8080:8080'
    depends_on:
      - analysis-db